#!/bin/sh

[ -f conf ] && . ./conf
exec /usr/share/jigasi/jigasi.sh \
	--host=$JIGASI_HOST --domain=$JIGASI_HOSTNAME --subdomain=callcontrol --secret=$JIGASI_SECRET \
	--logdir=$LOGDIR --configdir=/etc/jitsi --configdirname=jigasi $JIGASI_OPTS
